# Semana 4: Manipulación de datos

## Lectura de archivos

In [71]:
'''
Curso: Fundamentos de Python para Ciencia de Datos
Sesion 4: Manipulación de datos
Fecha: 26/04/2025
Autor: Godofredo Diaz
Email: gdiaz@tecsup.
'''

# Lectura de un archivo
archivo = open("/ejemplo1.txt","r")
archivo

# Tipo de tributos
print(type(archivo))
print(archivo.name)
print(archivo.mode)

# Lectura de datos de un archivo
print("------------------------------------------")
archivo_datos = archivo.read()
print(archivo_datos)
print(type(archivo_datos))

# Cerrar archivo
print("------------------------------------------")
archivo.close()
print(archivo)
print(type(archivo))

<class '_io.TextIOWrapper'>
/ejemplo1.txt
r
------------------------------------------
Linea 01
linea 02
LINEA 03
<class 'str'>
------------------------------------------
<_io.TextIOWrapper name='/ejemplo1.txt' mode='r' encoding='utf-8'>
<class '_io.TextIOWrapper'>

In [72]:
# Otra forma de leer archivos
print("------------------------------------------")
with open("/ejemplo1.txt","r") as archivo:
    contenido = archivo.read()
    print(contenido)

print(archivo.closed)
print(contenido)

------------------------------------------
Linea 01
linea 02
LINEA 03
True
Linea 01
linea 02
LINEA 03

In [73]:
# Lectura por fragmentos
print("------------------------------------------")
with open("/ejemplo1.txt","r") as archivo:
    print(archivo.read(4))

print("------------------------------------------")
with open("/ejemplo1.txt","r") as archivo:
    print(archivo.read(4))
    print(archivo.read(4))
    print(archivo.read(4))
    print(archivo.read(4))

------------------------------------------
Line
------------------------------------------
Line
a 01

lin
ea 0

In [74]:
# lectura por línea
print("------------------------------------------")
with open("/ejemplo1.txt","r") as archivo:
    print("Primera línea:",archivo.readline())

# lectura de todas las líneas
print("------------------------------------------")
with open("/ejemplo1.txt","r") as archivo:
    for linea in archivo:
        print("Línea:",linea)

# lectura de todas las líneas en una lista
print("------------------------------------------")
with open("/ejemplo1.txt","r") as archivo:
    contenido = archivo.readlines()
    print("Contenido:",contenido)

for linea in contenido:
    print(linea)

------------------------------------------
Primera línea: Linea 01

------------------------------------------
Línea: Linea 01

Línea: linea 02

Línea: LINEA 03
------------------------------------------
Contenido: ['Linea 01\n', 'linea 02\n', 'LINEA 03']
Linea 01

linea 02

LINEA 03

## Escritura de archivos

In [75]:
# Escritura en un archivo
print("------------------------------------------")
with open("/ejemplo2.txt","w") as archivo:
    archivo.write("Es una nueva línea")

------------------------------------------

In [76]:
# Escritura de más líneas en un archivo
print("------------------------------------------")
with open("/ejemplo2.txt","w") as archivo:
    archivo.write("Es una nueva línea 1")
    archivo.write("Es otra nueva línea 2")

------------------------------------------

In [77]:
# Escritura de más líneas en un archivo
print("------------------------------------------")
with open("/ejemplo2.txt","w") as archivo:
    archivo.write("Es una nueva línea \n")
    archivo.write("Es otra nueva línea \n")

------------------------------------------

In [78]:
# Agregar una línea en un archivo
print("------------------------------------------")
with open("/ejemplo2.txt","a") as archivo:
    archivo.write("Es otra nueva línea agregada \n")

------------------------------------------

In [79]:
# Copiar un archivo
print("------------------------------------------")
with open("/ejemplo2.txt","r") as archivo_origen:
    with open("/ejemplo3.txt","w") as archivo_destino:
        for linea in archivo_origen:
            archivo_destino.write(linea)

------------------------------------------

In [83]:
import csv
n_lineas =10
contador = 0
with open('/data.csv', newline='', encoding='latin-1') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')
    for row in spamreader:
        contador += 1
        print(', '.join(row))
        if contador > n_lineas:
            break

CODIGOENTIDAD, RUC_ENTIDAD, ENTIDAD, ENTIDAD_DEPARTAMENTO, ENTIDAD_PROVINCIA, ENTIDAD_DISTRITO, FECHACONVOCATORIA, OBJETOCONTRACTUAL, PROCESO, CODIGOCONVOCATORIA, DESCRIPCION_PROCESO, NUMERO_ITEM, ITEMCONVOCA_DESCRIPCION, ITEMCONVOCA_UNIDADMEDIDA, SECTOR, TIPOENTIDADOEE, TIPOPROCESO, ITEM_DEPARTAMENTO, ITEM_PROVINCIA, ITEM_DISTRITO, ESTADOITEMCONVOCA, ULTIMO, MONEDA, CAUSAL_EXOR_CONT_DIRECTA, MONTOREFERENCIAL, MONTOREFERENCIALSOLES, MONTOADJUDICADO, MONTOADJUDICADOSOLES, CANTIDADADJUDICADA, TIPOPROVEEDOR, RUCPROVEEDOR, PROVEEDOR, RUCDETALLEPROVEEDOR, DETALLEPROVEEDOR, URLFICHAPROCESO, CATEGORIA, SUBCATEGORIA
010146, 20481772550, POLICÖA NACIONAL DEL PERé - III REGIàN TERRITORIAL TRUJILLO, LA LIBERTAD, TRUJILLO, TRUJILLO, 03/04/20, Bien, DIRECTA-PROC-13-2020-III-DIRTEPOL-T-1, 607606, "ADQUISICION DE MATERIAL DE ASEO,  LIMPIEZA Y TOCADOR PARA LAS UNIDADES PNP DE LA REGPOL ANCASH Y  LA LIBERTAD  INTEGRANTE DE LA UE. 005-III-DIRTEPOL TRUJILLO", 1, "ADQUISICION DE MATERIAL DE ASEO,  LIMPIEZA Y TOCADOR DE LA REGION POLICIAL ANCASH Y LA LIBERTAD - PERTENECIENTES A LA  UE. N¨ 005 - ITEM PAQUETE I : XII MACRO REGION POLICIAL ANCASH", Unidad, INTERIOR, GOBIERNO NACIONAL, Contrataci¢n Directa, ANCASH, HUARAZ, HUARAZ, Contratado, ULTIMO, Soles, Situaci¢n emergencia, 105093, 105093, 105093, 105093, 4535, Persona Juridica, 20602348106, CORPORACION ALME E.I.R.L., , , http://prodapp2.seace.gob.pe/seacebus-uiwd-pub/fichaSeleccion/fichaSeleccion.xhtml?idSistema=3&ongei=1&idConvocatoria=607606, PROD. ASEO Y LIMPIEZA, PROD. ASEO Y LIMPIEZA
010146, 20481772550, POLICÖA NACIONAL DEL PERé - III REGIàN TERRITORIAL TRUJILLO, LA LIBERTAD, TRUJILLO, TRUJILLO, 03/04/20, Bien, DIRECTA-PROC-13-2020-III-DIRTEPOL-T-1, 607606, "ADQUISICION DE MATERIAL DE ASEO,  LIMPIEZA Y TOCADOR PARA LAS UNIDADES PNP DE LA REGPOL ANCASH Y  LA LIBERTAD  INTEGRANTE DE LA UE. 005-III-DIRTEPOL TRUJILLO", 2, "ADQUISICION DE MATERIAL DE ASEO,  LIMPIEZA Y TOCADOR DE LA REGION POLICIAL ANCASH Y LA LIBERTAD - PERTENECIENTES A LA UE. N¨ 005 - ITEM PAQUETE II : III MACRO REGION POLICIAL - LL", Unidad, INTERIOR, GOBIERNO NACIONAL, Contrataci¢n Directa, LA LIBERTAD, TRUJILLO, TRUJILLO, Contratado, ULTIMO, Soles, Situaci¢n emergencia, 114835, 114835, 114835, 114835, 4802, Persona Juridica, 20602348106, CORPORACION ALME E.I.R.L., , , http://prodapp2.seace.gob.pe/seacebus-uiwd-pub/fichaSeleccion/fichaSeleccion.xhtml?idSistema=3&ongei=1&idConvocatoria=607606, PROD. ASEO Y LIMPIEZA, PROD. ASEO Y LIMPIEZA
202925, 20601218471, GOBIERNO REGIONAL CAJAMARCA SALUD SAN IGNACIO, CAJAMARCA, SAN IGNACIO, SAN IGNACIO, 14/04/20, Bien, DIRECTA-PROC-1-2020-GRCAJ-DSRS/RSSI-1, 607637, "ADQUISICIàN DE 10000 UNIDADES DE MANDIL DESCARTABLE ESTERIL TALLA L PARA SER DISTRIBUIDO A LAS IPRESS DE LA UNIDAD EJECUTORA SALUD SAN IGNACIO,  EN EL MARCO DEL DECRETO SUPREMO Nø008-2020-SA.", 1, MANDIL DESCARTABLE ESTERIL L, Unidad, GOBIERNO REGIONAL, GOBIERNO REGIONAL, Contrataci¢n Directa, CAJAMARCA, SAN IGNACIO, SAN IGNACIO, Contratado, ULTIMO, Soles, Situaci¢n emergencia, 100000, 100000, 100000, 100000, 10000, Persona Juridica, 20601622549, CH & S MEDILAB SOCIEDAD ANONIMA CERRADA - CH & S MEDILAB S.A.C., , , http://prodapp2.seace.gob.pe/seacebus-uiwd-pub/fichaSeleccion/fichaSeleccion.xhtml?idSistema=3&ongei=1&idConvocatoria=607637, MATERIAL Y EQUIPO MEDICO, MATERIAL Y EQUIPO MEDICO
010154, 20370114952, POLICÖA NACIONAL DEL PERé - XI DIRECCIàN TERRITORIAL AREQUIPA, AREQUIPA, AREQUIPA, YANAHUARA, 23/03/20, Bien, DIRECTA-PROC-2-2020-UE-022-XI-DIRTE-1, 607678, "Adquisici¢n de diferentes bienes materiales de aseo (alcohol gel antisptico de mano y jab¢n l¡quido) y protecci¢n personal (mascarillas y guantes quir£rgicos de l tex) para las diferentes unidades y sub unidades de la PNP de las Regiones Policiales de Arequipa,  Moquegua y Tacna,  a consecuencia del brote COVID-19,  en atenci¢n al D. S. 044-2020-PCM", 1, MATERIALES DE PROTECCION (GUANTES Y MASCARILLAS), Unidad, INTERIOR, GOBIERNO NACIONAL, Contrataci¢n Directa, AREQUIPA, AREQUIPA, YANAHUARA, Contratado, ULTIMO, Soles, Situaci¢n emergencia, 503622, 503622, 503622, 503622, 143892, Persona Natural, 10458832400, BUITRON GUEVARA JENNIFER JANET, , , http://prodapp2.seace.gob.pe/seacebus-uiwd-pub/fichaSeleccion/fichaSeleccion.xhtml?idSistema=3&ongei=1&idConvocatoria=607678, MATERIAL Y EQUIPO MEDICO, MATERIAL Y EQUIPO MEDICO
010154, 20370114952, POLICÖA NACIONAL DEL PERé - XI DIRECCIàN TERRITORIAL AREQUIPA, AREQUIPA, AREQUIPA, YANAHUARA, 23/03/20, Bien, DIRECTA-PROC-2-2020-UE-022-XI-DIRTE-1, 607678, "Adquisici¢n de diferentes bienes materiales de aseo (alcohol gel antisptico de mano y jab¢n l¡quido) y protecci¢n personal (mascarillas y guantes quir£rgicos de l tex) para las diferentes unidades y sub unidades de la PNP de las Regiones Policiales de Arequipa,  Moquegua y Tacna,  a consecuencia del brote COVID-19,  en atenci¢n al D. S. 044-2020-PCM", 2, Alcohol gel antiseptico de mano, Unidad, INTERIOR, GOBIERNO NACIONAL, Contrataci¢n Directa, AREQUIPA, AREQUIPA, YANAHUARA, Contratado, ULTIMO, Soles, Situaci¢n emergencia, 231255, 231255, 231255, 231255, 10278, Persona Juridica, 20503850517, QUIMICA KAZVEL SOCIEDAD ANONIMA CERRADA - QUIMICA KAZVEL S.A.C., , , http://prodapp2.seace.gob.pe/seacebus-uiwd-pub/fichaSeleccion/fichaSeleccion.xhtml?idSistema=3&ongei=1&idConvocatoria=607678, PROD. ASEO Y LIMPIEZA, PROD. ASEO Y LIMPIEZA
010154, 20370114952, POLICÖA NACIONAL DEL PERé - XI DIRECCIàN TERRITORIAL AREQUIPA, AREQUIPA, AREQUIPA, YANAHUARA, 23/03/20, Bien, DIRECTA-PROC-2-2020-UE-022-XI-DIRTE-1, 607678, "Adquisici¢n de diferentes bienes materiales de aseo (alcohol gel antisptico de mano y jab¢n l¡quido) y protecci¢n personal (mascarillas y guantes quir£rgicos de l tex) para las diferentes unidades y sub unidades de la PNP de las Regiones Policiales de Arequipa,  Moquegua y Tacna,  a consecuencia del brote COVID-19,  en atenci¢n al D. S. 044-2020-PCM", 3, Jabon liquido, Unidad, INTERIOR, GOBIERNO NACIONAL, Contrataci¢n Directa, AREQUIPA, AREQUIPA, YANAHUARA, Contratado, ULTIMO, Soles, Situaci¢n emergencia, 65059.74, 65059.74, 65059.74, 65059.74, 10278, Persona Natural, 10708299532, CORNEJO PORTUGAL SUE LEONOR, , , http://prodapp2.seace.gob.pe/seacebus-uiwd-pub/fichaSeleccion/fichaSeleccion.xhtml?idSistema=3&ongei=1&idConvocatoria=607678, PROD. ASEO Y LIMPIEZA, PROD. ASEO Y LIMPIEZA
010143, 20165465009, POLICIA NACIONAL DEL PERé - DIRECCIàN DE ECONOMÖA Y FINANZAS, LIMA, LIMA, RIMAC, 26/03/20, Bien, DIRECTA-PROC-3-2020-DIRECFIN-PNP-1, 607688, "ADQUISICIàN DE IMPLEMENTOS DE PREVENCIàN PARA EL PERSONAL PNP,  QUE PRESTA SERVICIOS EN LAS DIFERENTES UNIDADES DE LA UNIDAD EJECUTORA 002 DIRECFIN PNP", 1, "ITEM 1 - IMPLEMENTOS DE PREVENCI¨N PARA LAS DIFERENTES UNIDADES PERTENECIENTES A LA UE N¨002-DIRECFIN-PNP: COMGEN,  SUBCOMGEN,  SECGEN,  EMG,  OCI,  SECEJE,  UNITRADOC,  DIREASJUR,  DIRPLAINS,  DIRADM,  DIVLOG,  DIVECO Y DIVINFRA.", Unidad, INTERIOR, GOBIERNO NACIONAL, Contrataci¢n Directa, LIMA, LIMA, RIMAC, Contratado, ULTIMO, Soles, Situaci¢n emergencia, 1553000, 1553000, 1553000, 1553000, 1, Persona Natural, 10458832400, BUITRON GUEVARA JENNIFER JANET, , , http://prodapp2.seace.gob.pe/seacebus-uiwd-pub/fichaSeleccion/fichaSeleccion.xhtml?idSistema=3&ongei=1&idConvocatoria=607688, PROD. ASEO Y LIMPIEZA, PROD. ASEO Y LIMPIEZA
010143, 20165465009, POLICIA NACIONAL DEL PERé - DIRECCIàN DE ECONOMÖA Y FINANZAS, LIMA, LIMA, RIMAC, 26/03/20, Bien, DIRECTA-PROC-3-2020-DIRECFIN-PNP-1, 607688, "ADQUISICIàN DE IMPLEMENTOS DE PREVENCIàN PARA EL PERSONAL PNP,  QUE PRESTA SERVICIOS EN LAS DIFERENTES UNIDADES DE LA UNIDAD EJECUTORA 002 DIRECFIN PNP", 2, "ITEM 2 - IMPLEMENTOS DE PREVENCI¨N PARA LAS DIFERENTES UNIDADES PERTENECIENTES A LA UE N¨002-DIRECFIN-PNP: DIRNOS,  DIRSEEST,  DIRSCPC,  DIVPNA,  DIVCVF.", Unidad, INTERIOR, GOBIERNO NACIONAL, Contrataci¢n Directa, LIMA, LIMA, RIMAC, Contratado, ULTIMO, Soles, Situaci¢n emergencia, 619990, 619990, 619990, 619990, 1, Persona Juridica, 20604291756, D'JAVA NEGOCIOS E.I.R.L., , , http://prodapp2.seace.gob.pe/seacebus-uiwd-pub/fichaSeleccion/fichaSeleccion.xhtml?idSistema=3&ongei=1&idConvocatoria=607688, PROD. ASEO Y LIMPIEZA, PROD. ASEO Y LIMPIEZA
010143, 20165465009, POLICIA NACIONAL DEL PERé - DIRECCIàN DE ECONOMÖA Y FINANZAS, LIMA, LIMA, RIMAC, 26/03/20, Bien, DIRECTA-PROC-3-2020-DIRECFIN-PNP-1, 607688, "ADQUISICIàN DE IMPLEMENTOS DE PREVENCIàN PARA EL PERSONAL PNP,  QUE PRESTA SERVICIOS EN LAS DIFERENTES UNIDADES DE LA UNIDAD EJECUTORA 002 DIRECFIN PNP", 3, "ITEM 3 - IMPLEMENTOS DE PREVENCI¨N PARA LAS DIFERENTES UNIDADES PERTENECIENTES A LA UE N¨002-DIRECFIN-PNP: IG,  DIRREHUM,  DIRBAP,  DIVPEN,  DIRIN,  DIRTTSV, DIVPRCAR,  DIVSEFER.", Unidad, INTERIOR, GOBIERNO NACIONAL, Contrataci¢n Directa, LIMA, LIMA, RIMAC, Contratado, ULTIMO, Soles, Situaci¢n emergencia, 2758200, 2758200, 2749200, 2749200, 1, Persona Juridica, 20548606331, NIEVA TRADING S.R.L., , , http://prodapp2.seace.gob.pe/seacebus-uiwd-pub/fichaSeleccion/fichaSeleccion.xhtml?idSistema=3&ongei=1&idConvocatoria=607688, PROD. ASEO Y LIMPIEZA, PROD. ASEO Y LIMPIEZA
010247, 20131369124, EJERCITO PERUANO, LIMA, LIMA, SAN BORJA, 03/04/20, Bien, DIRECTA-PROC-1-2020-EP/UO 0804-1, 607716, ADQUISICION DE ALIMENTOS PARA PERSONAS POR DECLARATORIA DE EMERGENCIA SANITARIA, 1, Alimentos derivados de la situaci¨n de emergencia por graves circunstancias que afectan la vida de la Naci¨n a consecuencia del brote del COVID-19, Unidad, DEFENSA, GOBIERNO NACIONAL, Contrataci¢n Directa, TUMBES, TUMBES, TUMBES, Contratado, ULTIMO, Soles, Situaci¢n emergencia, 293400, 293400, 293400, 293400, 5, Persona Juridica, 20481368341, DISTRIBUIDORA FINA SRL, , , http://prodapp2.seace.gob.pe/seacebus-uiwd-pub/fichaSeleccion/fichaSeleccion.xhtml?idSistema=3&ongei=1&idConvocatoria=607716, ALIMENTOS, OTROS ALIMENTOS

## Librería Pandas

In [85]:
# Convertir lista de listas a data frame
import pandas as pd
df = pd.DataFrame([['María', 18], ['Luis', 22], ['Carmen', 20]],
                  columns=['Nombre', 'Edad'])
print(df)

   Nombre  Edad
0   María    18
1    Luis    22
2  Carmen    20

In [86]:
# Convertir lista de diccionarios a data frame
df = pd.DataFrame([{'Nombre':'María', 'Edad':18}, {'Nombre':'Luis', 'Edad':22},
                   {'Nombre':'Carmen'}])
print(df)

   Nombre  Edad
0   María  18.0
1    Luis  22.0
2  Carmen   NaN

In [87]:
# Convertir diccionario de listas a data frame
datos = {'Nombre':['María', 'Luis', 'Carmen', 'Antonio'],
         'Edad':[18, 22, 20, 21],
         'Grado':['Economía', 'Medicina', 'Arquitectura', 'Economía'],
         'Correo':['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com',
                   'antonio@gmail.com']
        }
df = pd.DataFrame(datos)
print(df)

    Nombre  Edad         Grado             Correo
0    María    18      Economía    maria@gmail.com
1     Luis    22      Medicina      luis@yahoo.es
2   Carmen    20  Arquitectura   carmen@gmail.com
3  Antonio    21      Economía  antonio@gmail.com

In [ ]:
# Convertir array a data frame
import numpy as np
df = pd.DataFrame(np.random.randn(4, 3), columns=['a', 'b', 'c'])
print(df)

          a         b         c
0  1.107092  0.956142  0.523991
1  0.137730 -0.821458  1.445655
2  0.791094 -1.277342 -0.259153
3 -2.674767 -0.406210  0.119942

In [90]:
# Leer archivo CSV
print("------------------------------------------")
archivo_csv = "/medallero_Panamericanos_Lima2019.csv"
#df = pd.read_csv(archivo_csv)
df = pd.read_csv(archivo_csv, encoding='cp1252')
print(df.head())
print(df.keys())

------------------------------------------
   Posicion            Pais  Oro  Plata  Bronce  Total  Ranking Total
0         1  Estados Unidos  120     88      85    293              1
1         2          Brasil   55     45      71    171              2
2         3          M‚xico   37     36      63    136              4
3         4          Canad    35     64      53    152              3
4         5            Cuba   33     27      38     98              6
Index(['Posicion', 'Pais', 'Oro', 'Plata', 'Bronce', 'Total', 'Ranking Total'], dtype='object')

In [91]:
# Leer una columna del archivo: Series
print("------------------------------------------")
col_pais = df["Pais"]
print(type(col_pais))
print(col_pais)

# Leer una columna del archivo: Data frame
print("------------------------------------------")
medallas = df[["Pais","Oro","Plata","Bronce"]]
print(type(medallas))
print(medallas)

------------------------------------------
<class 'pandas.core.series.Series'>
0           Estados Unidos
1                   Brasil
2                   M‚xico
3                   Canad
4                     Cuba
5                Argentina
6                 Colombia
7                    Chile
8                     Per£
9     Rep£blica Dominicana
10                 Ecuador
11               Venezuela
12                 Jamaica
13             Puerto Rico
14             El Salvador
15               Guatemala
16       Trinidad y Tobago
17                 Uruguay
18                Paraguay
19                 Bolivia
20                 Granada
21              Costa Rica
22             Santa Lucia
23                Barbados
24          Islas V¡rgenes
25       Antigua y Barbuda
26                Honduras
27                  Panam
28               Nicaragua
29                   Aruba
30                 Bahamas
Name: Pais, dtype: object
------------------------------------------
<class 'pandas.core.frame.DataFrame'>
                    Pais  Oro  Plata  Bronce
0         Estados Unidos  120     88      85
1                 Brasil   55     45      71
2                 M‚xico   37     36      63
3                 Canad    35     64      53
4                   Cuba   33     27      38
5              Argentina   32     35      34
6               Colombia   28     23      33
7                  Chile   13     19      18
8                   Per£   11      7      21
9   Rep£blica Dominicana   10     13      17
10               Ecuador   10      7      14
11             Venezuela    9     15      19
12               Jamaica    6      6       7
13           Puerto Rico    5      5      14
14           El Salvador    3      0       1
15             Guatemala    2      9       8
16     Trinidad y Tobago    2      8       3
17               Uruguay    1      4       4
18              Paraguay    1      3       1
19               Bolivia    1      2       2
20               Granada    1      1       0
21            Costa Rica    1      0       4
22           Santa Lucia    1      0       1
23              Barbados    1      0       0
24        Islas V¡rgenes    1      0       0
25     Antigua y Barbuda    0      1       2
26              Honduras    0      1       1
27                Panam     0      0       4
28             Nicaragua    0      0       3
29                 Aruba    0      0       1
30               Bahamas    0      0       1

In [92]:
# leer una fila
print("------------------------------------------")
print(df.head())

print("------------------------------------------")
x = 0
dato = df.iloc[x]
print(type(dato))
print(dato)

print("------------------------------------------")
x = 1
dato = df.iloc[x]
print(type(dato))
print(dato)

------------------------------------------
   Posicion            Pais  Oro  Plata  Bronce  Total  Ranking Total
0         1  Estados Unidos  120     88      85    293              1
1         2          Brasil   55     45      71    171              2
2         3          M‚xico   37     36      63    136              4
3         4          Canad    35     64      53    152              3
4         5            Cuba   33     27      38     98              6
------------------------------------------
<class 'pandas.core.series.Series'>
Posicion                      1
Pais             Estados Unidos
Oro                         120
Plata                        88
Bronce                       85
Total                       293
Ranking Total                 1
Name: 0, dtype: object
------------------------------------------
<class 'pandas.core.series.Series'>
Posicion              2
Pais             Brasil
Oro                  55
Plata                45
Bronce               71
Total               171
Ranking Total         2
Name: 1, dtype: object

In [ ]:
# Leer una columna
print("------------------------------------------")
print(df.head())

print("------------------------------------------")
x = 0
dato = df.iloc[:,x]
print(type(dato))
print(dato)

print("------------------------------------------")
x = 1
dato = df.iloc[:,x]
print(type(dato))
print(dato)

------------------------------------------
   Posicion            Pais  Oro  Plata  Bronce  Total  Ranking Total
0         1  Estados Unidos  120     88      85    293              1
1         2          Brasil   55     45      71    171              2
2         3          M‚xico   37     36      63    136              4
3         4          Canad    35     64      53    152              3
4         5            Cuba   33     27      38     98              6
------------------------------------------
<class 'pandas.core.series.Series'>
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    24
25    26
26    27
27    28
28    29
29    30
30    30
Name: Posicion, dtype: int64
------------------------------------------
<class 'pandas.core.series.Series'>
0           Estados Unidos
1                   Brasil
2                   M‚xico
3                   Canad
4                     Cuba
5                Argentina
6                 Colombia
7                    Chile
8                     Per£
9     Rep£blica Dominicana
10                 Ecuador
11               Venezuela
12                 Jamaica
13             Puerto Rico
14             El Salvador
15               Guatemala
16       Trinidad y Tobago
17                 Uruguay
18                Paraguay
19                 Bolivia
20                 Granada
21              Costa Rica
22             Santa Lucia
23                Barbados
24          Islas V¡rgenes
25       Antigua y Barbuda
26                Honduras
27                  Panam
28               Nicaragua
29                   Aruba
30                 Bahamas
Name: Pais, dtype: object

In [ ]:
# Leer múltiples filas y columnas
print("------------------------------------------")
print(df.head())

print("------------------------------------------")
dato = df.iloc[0:2]
print(type(dato))
print(dato)

print("------------------------------------------")
dato = df.iloc[:,0:3]
print(type(dato))
print(dato)

print("------------------------------------------")
dato = df.iloc[0:2,0:3]
print(type(dato))
print(dato)

------------------------------------------
   Posicion            Pais  Oro  Plata  Bronce  Total  Ranking Total
0         1  Estados Unidos  120     88      85    293              1
1         2          Brasil   55     45      71    171              2
2         3          M‚xico   37     36      63    136              4
3         4          Canad    35     64      53    152              3
4         5            Cuba   33     27      38     98              6
------------------------------------------
<class 'pandas.core.frame.DataFrame'>
   Posicion            Pais  Oro  Plata  Bronce  Total  Ranking Total
0         1  Estados Unidos  120     88      85    293              1
1         2          Brasil   55     45      71    171              2
------------------------------------------
<class 'pandas.core.frame.DataFrame'>
    Posicion                  Pais  Oro
0          1        Estados Unidos  120
1          2                Brasil   55
2          3                M‚xico   37
3          4                Canad    35
4          5                  Cuba   33
5          6             Argentina   32
6          7              Colombia   28
7          8                 Chile   13
8          9                  Per£   11
9         10  Rep£blica Dominicana   10
10        11               Ecuador   10
11        12             Venezuela    9
12        13               Jamaica    6
13        14           Puerto Rico    5
14        15           El Salvador    3
15        16             Guatemala    2
16        17     Trinidad y Tobago    2
17        18               Uruguay    1
18        19              Paraguay    1
19        20               Bolivia    1
20        21               Granada    1
21        22            Costa Rica    1
22        23           Santa Lucia    1
23        24              Barbados    1
24        24        Islas V¡rgenes    1
25        26     Antigua y Barbuda    0
26        27              Honduras    0
27        28                Panam     0
28        29             Nicaragua    0
29        30                 Aruba    0
30        30               Bahamas    0
------------------------------------------
<class 'pandas.core.frame.DataFrame'>
   Posicion            Pais  Oro
0         1  Estados Unidos  120
1         2          Brasil   55

In [ ]:
# Filtros por columnas 1
print("------------------------------------------")
print(df.head())

print("------------------------------------------")
df.set_index("Pais",inplace=True)
print(df.head())

print("------------------------------------------")
dato = df.loc["Brasil"]
print(type(dato))
print(dato)

------------------------------------------
   Posicion            Pais  Oro  Plata  Bronce  Total  Ranking Total
0         1  Estados Unidos  120     88      85    293              1
1         2          Brasil   55     45      71    171              2
2         3          M‚xico   37     36      63    136              4
3         4          Canad    35     64      53    152              3
4         5            Cuba   33     27      38     98              6
------------------------------------------
                Posicion  Oro  Plata  Bronce  Total  Ranking Total
Pais
Estados Unidos         1  120     88      85    293              1
Brasil                 2   55     45      71    171              2
M‚xico                 3   37     36      63    136              4
Canad                  4   35     64      53    152              3
Cuba                   5   33     27      38     98              6
------------------------------------------
<class 'pandas.core.series.Series'>
Posicion           2
Oro               55
Plata             45
Bronce            71
Total            171
Ranking Total      2
Name: Brasil, dtype: int64

In [ ]:
# Filtros por columnas 2
print("------------------------------------------")
print(df.head())

#print("------------------------------------------")
#df.set_index("Pais",inplace=True)
#print(df.head())

print("------------------------------------------")
dato = df.loc[["Brasil","Cuba"]]
print(type(dato))
print(dato)

------------------------------------------
                Posicion  Oro  Plata  Bronce  Total  Ranking Total
Pais
Estados Unidos         1  120     88      85    293              1
Brasil                 2   55     45      71    171              2
M‚xico                 3   37     36      63    136              4
Canad                  4   35     64      53    152              3
Cuba                   5   33     27      38     98              6
------------------------------------------
<class 'pandas.core.frame.DataFrame'>
        Posicion  Oro  Plata  Bronce  Total  Ranking Total
Pais
Brasil         2   55     45      71    171              2
Cuba           5   33     27      38     98              6

In [ ]:
# Filtros por columnas 3
print("------------------------------------------")
print(df.head())

#print("------------------------------------------")
#df.set_index("Pais",inplace=True)
#print(df.head())

print("------------------------------------------")
dato = df.loc[["Brasil","Cuba"],["Oro","Plata","Bronce"]]
print(type(dato))
print(dato)

------------------------------------------
                Posicion  Oro  Plata  Bronce  Total  Ranking Total
Pais
Estados Unidos         1  120     88      85    293              1
Brasil                 2   55     45      71    171              2
M‚xico                 3   37     36      63    136              4
Canad                  4   35     64      53    152              3
Cuba                   5   33     27      38     98              6
------------------------------------------
<class 'pandas.core.frame.DataFrame'>
        Oro  Plata  Bronce
Pais
Brasil   55     45      71
Cuba     33     27      38

In [ ]:
# Filtros por columnas 4
print("------------------------------------------")
print(df.head())

#print("------------------------------------------")
#df.set_index("Pais",inplace=True)
#print(df.head())

print("------------------------------------------")
dato = df.loc[df["Plata"] == 1,["Oro","Plata","Bronce"]]
print(type(dato))
print(dato)

------------------------------------------
                Posicion  Oro  Plata  Bronce  Total  Ranking Total
Pais
Estados Unidos         1  120     88      85    293              1
Brasil                 2   55     45      71    171              2
M‚xico                 3   37     36      63    136              4
Canad                  4   35     64      53    152              3
Cuba                   5   33     27      38     98              6
------------------------------------------
<class 'pandas.core.frame.DataFrame'>
                   Oro  Plata  Bronce
Pais
Granada              1      1       0
Antigua y Barbuda    0      1       2
Honduras             0      1       1

In [ ]:
# Filtros por columnas 5
print("---------------------------------")
print(df.head ())

#print("---------------------------------")
#df.set_index ("Pais", inplace=True)
#print(df.head ())

print("---------------------------------")
dato = df.loc[df["Oro"] > 10 ,["Oro","Plata","Bronce"]]
print(type(dato))
print(dato)

---------------------------------
                Posicion  Oro  Plata  Bronce  Total  Ranking Total
Pais
Estados Unidos         1  120     88      85    293              1
Brasil                 2   55     45      71    171              2
M‚xico                 3   37     36      63    136              4
Canad                  4   35     64      53    152              3
Cuba                   5   33     27      38     98              6
---------------------------------
<class 'pandas.core.frame.DataFrame'>
                Oro  Plata  Bronce
Pais
Estados Unidos  120     88      85
Brasil           55     45      71
M‚xico           37     36      63
Canad            35     64      53
Cuba             33     27      38
Argentina        32     35      34
Colombia         28     23      33
Chile            13     19      18
Per£             11      7      21

In [ ]:
# Filtros por columnas 6
print("---------------------------------")
print(df.head ())

#print("---------------------------------")
#df.set_index ("Pais", inplace=True)
#print(df.head ())

print("---------------------------------")
dato = df.loc[(df["Oro"] > 10) & (df["Oro"] < 30),["Oro","Plata","Bronce"]]
print(type(dato))
print(dato)

---------------------------------
                Posicion  Oro  Plata  Bronce  Total  Ranking Total
Pais
Estados Unidos         1  120     88      85    293              1
Brasil                 2   55     45      71    171              2
M‚xico                 3   37     36      63    136              4
Canad                  4   35     64      53    152              3
Cuba                   5   33     27      38     98              6
---------------------------------
<class 'pandas.core.frame.DataFrame'>
          Oro  Plata  Bronce
Pais
Colombia   28     23      33
Chile      13     19      18
Per£       11      7      21

In [ ]:
print("------------------------------------------")
archivo_csv = "/medallero_Panamericanos_Lima2019.csv"
df = pd.read_csv(archivo_csv, encoding='cp1252')
print(len(df))
print(df.head())

------------------------------------------
31
   Posicion            Pais  Oro  Plata  Bronce  Total  Ranking Total
0         1  Estados Unidos  120     88      85    293              1
1         2          Brasil   55     45      71    171              2
2         3          M‚xico   37     36      63    136              4
3         4          Canad    35     64      53    152              3
4         5            Cuba   33     27      38     98              6

In [ ]:
# Renombrar filas y columnas
df.rename(columns={'Oro':'Primero', 'Plata':'Segundo', 'Bronce':'Tercero'},
          index={0:30, 1:29, 2:28}, inplace=True)
print(df.head())

    Posicion            Pais  Primero  Segundo  Tercero  Total  Ranking Total
30         1  Estados Unidos      120       88       85    293              1
29         2          Brasil       55       45       71    171              2
28         3          M‚xico       37       36       63    136              4
3          4          Canad        35       64       53    152              3
4          5            Cuba       33       27       38     98              6

In [ ]:
'''# Reindexar data frame
df.reindex(index=[4, 3], columns=['Pais', 'Cuarto', 'Ranking Total'])
print(df)'''

"# Reindexar data frame\ndf.reindex(index=[4, 3], columns=['Pais', 'Cuarto', 'Ranking Total'])\nprint(df)"

In [ ]:
# Operaciones sobre columnas
print("------------------------------------------")
print(df['Total'] + 5)

print("------------------------------------------")
print(df['Ranking Total']*2)

print("------------------------------------------")
print(df['Primero'].apply(lambda x : x + 2))

print("------------------------------------------")
def multi(x):
    return x * 3

print(df['Primero'].apply(multi))

------------------------------------------
30    298
29    176
28    141
3     157
4     103
5     106
6      89
7      55
8      44
9      45
10     36
11     48
12     24
13     29
14      9
15     24
16     18
17     14
18     10
19     10
20      7
21     10
22      7
23      6
24      6
25      8
26      7
27      9
28      8
29      6
30      6
Name: Total, dtype: int64
------------------------------------------
30     2
29     4
28     8
3      6
4     12
5     10
6     14
7     16
8     22
9     20
10    24
11    18
12    28
13    26
14    42
15    28
16    32
17    34
18    36
19    36
20    50
21    36
22    50
23    56
24    56
25    46
26    50
27    42
28    46
29    56
30    56
Name: Ranking Total, dtype: int64
------------------------------------------
30    122
29     57
28     39
3      37
4      35
5      34
6      30
7      15
8      13
9      12
10     12
11     11
12      8
13      7
14      5
15      4
16      4
17      3
18      3
19      3
20      3
21      3
22      3
23      3
24      3
25      2
26      2
27      2
28      2
29      2
30      2
Name: Primero, dtype: int64
------------------------------------------
30    360
29    165
28    111
3     105
4      99
5      96
6      84
7      39
8      33
9      30
10     30
11     27
12     18
13     15
14      9
15      6
16      6
17      3
18      3
19      3
20      3
21      3
22      3
23      3
24      3
25      0
26      0
27      0
28      0
29      0
30      0
Name: Primero, dtype: int64

In [ ]:
# Agregar columnas
print("------------------------------------------")
df['Nueva'] = pd.Series(np.zeros(len(df)))
print(df)

------------------------------------------
    Posicion                  Pais  Primero  Segundo  Tercero  Total  \
30         1        Estados Unidos      120       88       85    293
29         2                Brasil       55       45       71    171
28         3                M‚xico       37       36       63    136
3          4                Canad        35       64       53    152
4          5                  Cuba       33       27       38     98
5          6             Argentina       32       35       34    101
6          7              Colombia       28       23       33     84
7          8                 Chile       13       19       18     50
8          9                  Per£       11        7       21     39
9         10  Rep£blica Dominicana       10       13       17     40
10        11               Ecuador       10        7       14     31
11        12             Venezuela        9       15       19     43
12        13               Jamaica        6        6        7     19
13        14           Puerto Rico        5        5       14     24
14        15           El Salvador        3        0        1      4
15        16             Guatemala        2        9        8     19
16        17     Trinidad y Tobago        2        8        3     13
17        18               Uruguay        1        4        4      9
18        19              Paraguay        1        3        1      5
19        20               Bolivia        1        2        2      5
20        21               Granada        1        1        0      2
21        22            Costa Rica        1        0        4      5
22        23           Santa Lucia        1        0        1      2
23        24              Barbados        1        0        0      1
24        24        Islas V¡rgenes        1        0        0      1
25        26     Antigua y Barbuda        0        1        2      3
26        27              Honduras        0        1        1      2
27        28                Panam         0        0        4      4
28        29             Nicaragua        0        0        3      3
29        30                 Aruba        0        0        1      1
30        30               Bahamas        0        0        1      1

    Ranking Total  Nueva
30              1    0.0
29              2    0.0
28              4    0.0
3               3    0.0
4               6    0.0
5               5    0.0
6               7    0.0
7               8    0.0
8              11    0.0
9              10    0.0
10             12    0.0
11              9    0.0
12             14    0.0
13             13    0.0
14             21    0.0
15             14    0.0
16             16    0.0
17             17    0.0
18             18    0.0
19             18    0.0
20             25    0.0
21             18    0.0
22             25    0.0
23             28    0.0
24             28    0.0
25             23    0.0
26             25    0.0
27             21    0.0
28             23    0.0
29             28    0.0
30             28    0.0

In [ ]:
# Eliminar columnas
print("------------------------------------------")
del df['Total']
print(df.head())

------------------------------------------
    Posicion            Pais  Primero  Segundo  Tercero  Ranking Total  Nueva
30         1  Estados Unidos      120       88       85              1    0.0
29         2          Brasil       55       45       71              2    0.0
28         3          M‚xico       37       36       63              4    0.0
3          4          Canad        35       64       53              3    0.0
4          5            Cuba       33       27       38              6    0.0

In [ ]:
print("------------------------------------------")
df.pop('Ranking Total')
print(df.head())

------------------------------------------
    Posicion            Pais  Primero  Segundo  Tercero  Nueva
30         1  Estados Unidos      120       88       85    0.0
29         2          Brasil       55       45       71    0.0
28         3          M‚xico       37       36       63    0.0
3          4          Canad        35       64       53    0.0
4          5            Cuba       33       27       38    0.0

In [ ]:
df.shape

(31, 6)

In [ ]:
# Añadir filas a un data frame
registro_nuevo = {'Posicion':32,'Pais':'Surinam','Primero':0,
                  'Segundo':0,'Tercero':0}
df.loc[len(df)] = registro_nuevo
df = df.reset_index(drop=True)
print(df)

    Posicion                  Pais  Primero  Segundo  Tercero  Nueva
0          1        Estados Unidos      120       88       85    0.0
1          2                Brasil       55       45       71    0.0
2          3                M‚xico       37       36       63    0.0
3          4                Canad        35       64       53    0.0
4          5                  Cuba       33       27       38    0.0
5          6             Argentina       32       35       34    0.0
6          7              Colombia       28       23       33    0.0
7          8                 Chile       13       19       18    0.0
8          9                  Per£       11        7       21    0.0
9         10  Rep£blica Dominicana       10       13       17    0.0
10        11               Ecuador       10        7       14    0.0
11        12             Venezuela        9       15       19    0.0
12        13               Jamaica        6        6        7    0.0
13        14           Puerto Rico        5        5       14    0.0
14        15           El Salvador        3        0        1    0.0
15        16             Guatemala        2        9        8    0.0
16        17     Trinidad y Tobago        2        8        3    0.0
17        18               Uruguay        1        4        4    0.0
18        19              Paraguay        1        3        1    0.0
19        20               Bolivia        1        2        2    0.0
20        21               Granada        1        1        0    0.0
21        22            Costa Rica        1        0        4    0.0
22        23           Santa Lucia        1        0        1    0.0
23        24              Barbados        1        0        0    0.0
24        24        Islas V¡rgenes        1        0        0    0.0
25        26     Antigua y Barbuda        0        1        2    0.0
26        27              Honduras        0        1        1    0.0
27        28                Panam         0        0        4    0.0
28        29             Nicaragua        0        0        3    0.0
29        30                 Aruba        0        0        1    0.0
30        30               Bahamas        0        0        1    0.0
31        32               Surinam        0        0        0    NaN

In [ ]:
# Eliminar filas de un data frame
print("------------------------------------------")
print(df.drop([30, 29, 28]))

------------------------------------------
    Posicion                  Pais  Primero  Segundo  Tercero  Nueva
0          1        Estados Unidos      120       88       85    0.0
1          2                Brasil       55       45       71    0.0
2          3                M‚xico       37       36       63    0.0
3          4                Canad        35       64       53    0.0
4          5                  Cuba       33       27       38    0.0
5          6             Argentina       32       35       34    0.0
6          7              Colombia       28       23       33    0.0
7          8                 Chile       13       19       18    0.0
8          9                  Per£       11        7       21    0.0
9         10  Rep£blica Dominicana       10       13       17    0.0
10        11               Ecuador       10        7       14    0.0
11        12             Venezuela        9       15       19    0.0
12        13               Jamaica        6        6        7    0.0
13        14           Puerto Rico        5        5       14    0.0
14        15           El Salvador        3        0        1    0.0
15        16             Guatemala        2        9        8    0.0
16        17     Trinidad y Tobago        2        8        3    0.0
17        18               Uruguay        1        4        4    0.0
18        19              Paraguay        1        3        1    0.0
19        20               Bolivia        1        2        2    0.0
20        21               Granada        1        1        0    0.0
21        22            Costa Rica        1        0        4    0.0
22        23           Santa Lucia        1        0        1    0.0
23        24              Barbados        1        0        0    0.0
24        24        Islas V¡rgenes        1        0        0    0.0
25        26     Antigua y Barbuda        0        1        2    0.0
26        27              Honduras        0        1        1    0.0
27        28                Panam         0        0        4    0.0
31        32               Surinam        0        0        0    NaN

In [ ]:
# Ordenar por columnas
print("------------------------------------------")
print(df.sort_values('Tercero',ascending=False))

print("------------------------------------------")
print(df.sort_index(ascending=False))

------------------------------------------
    Posicion                  Pais  Primero  Segundo  Tercero  Nueva
0          1        Estados Unidos      120       88       85    0.0
1          2                Brasil       55       45       71    0.0
2          3                M‚xico       37       36       63    0.0
3          4                Canad        35       64       53    0.0
4          5                  Cuba       33       27       38    0.0
5          6             Argentina       32       35       34    0.0
6          7              Colombia       28       23       33    0.0
8          9                  Per£       11        7       21    0.0
11        12             Venezuela        9       15       19    0.0
7          8                 Chile       13       19       18    0.0
9         10  Rep£blica Dominicana       10       13       17    0.0
10        11               Ecuador       10        7       14    0.0
13        14           Puerto Rico        5        5       14    0.0
15        16             Guatemala        2        9        8    0.0
12        13               Jamaica        6        6        7    0.0
17        18               Uruguay        1        4        4    0.0
27        28                Panam         0        0        4    0.0
21        22            Costa Rica        1        0        4    0.0
28        29             Nicaragua        0        0        3    0.0
16        17     Trinidad y Tobago        2        8        3    0.0
19        20               Bolivia        1        2        2    0.0
25        26     Antigua y Barbuda        0        1        2    0.0
14        15           El Salvador        3        0        1    0.0
18        19              Paraguay        1        3        1    0.0
30        30               Bahamas        0        0        1    0.0
29        30                 Aruba        0        0        1    0.0
22        23           Santa Lucia        1        0        1    0.0
26        27              Honduras        0        1        1    0.0
23        24              Barbados        1        0        0    0.0
20        21               Granada        1        1        0    0.0
24        24        Islas V¡rgenes        1        0        0    0.0
31        32               Surinam        0        0        0    NaN
------------------------------------------
    Posicion                  Pais  Primero  Segundo  Tercero  Nueva
31        32               Surinam        0        0        0    NaN
30        30               Bahamas        0        0        1    0.0
29        30                 Aruba        0        0        1    0.0
28        29             Nicaragua        0        0        3    0.0
27        28                Panam         0        0        4    0.0
26        27              Honduras        0        1        1    0.0
25        26     Antigua y Barbuda        0        1        2    0.0
24        24        Islas V¡rgenes        1        0        0    0.0
23        24              Barbados        1        0        0    0.0
22        23           Santa Lucia        1        0        1    0.0
21        22            Costa Rica        1        0        4    0.0
20        21               Granada        1        1        0    0.0
19        20               Bolivia        1        2        2    0.0
18        19              Paraguay        1        3        1    0.0
17        18               Uruguay        1        4        4    0.0
16        17     Trinidad y Tobago        2        8        3    0.0
15        16             Guatemala        2        9        8    0.0
14        15           El Salvador        3        0        1    0.0
13        14           Puerto Rico        5        5       14    0.0
12        13               Jamaica        6        6        7    0.0
11        12             Venezuela        9       15       19    0.0
10        11               Ecuador       10        7       14    0.0
9         10  Rep£blica Dominicana       10       13       17    0.0
8          9                  Per£       11        7       21    0.0
7          8                 Chile       13       19       18    0.0
6          7              Colombia       28       23       33    0.0
5          6             Argentina       32       35       34    0.0
4          5                  Cuba       33       27       38    0.0
3          4                Canad        35       64       53    0.0
2          3                M‚xico       37       36       63    0.0
1          2                Brasil       55       45       71    0.0
0          1        Estados Unidos      120       88       85    0.0

In [ ]:
# Dividir data frame en grupos
print("------------------------------------------")
print(df.groupby('Primero').groups)

print("------------------------------------------")
print(df.groupby(['Primero','Segundo']).groups)

print("------------------------------------------")
print(df.groupby('Primero').get_group(0))

print("------------------------------------------")
df = df.drop(['Pais'],axis=1)
print(df.groupby('Primero').agg(np.mean))

------------------------------------------
{0: [25, 26, 27, 28, 29, 30, 31], 1: [17, 18, 19, 20, 21, 22, 23, 24], 2: [15, 16], 3: [14], 5: [13], 6: [12], 9: [11], 10: [9, 10], 11: [8], 13: [7], 28: [6], 32: [5], 33: [4], 35: [3], 37: [2], 55: [1], 120: [0]}
------------------------------------------
{(0, 0): [27, 28, 29, 30, 31], (0, 1): [25, 26], (1, 0): [21, 22, 23, 24], (1, 1): [20], (1, 2): [19], (1, 3): [18], (1, 4): [17], (2, 8): [16], (2, 9): [15], (3, 0): [14], (5, 5): [13], (6, 6): [12], (9, 15): [11], (10, 7): [10], (10, 13): [9], (11, 7): [8], (13, 19): [7], (28, 23): [6], (32, 35): [5], (33, 27): [4], (35, 64): [3], (37, 36): [2], (55, 45): [1], (120, 88): [0]}
------------------------------------------
    Posicion               Pais  Primero  Segundo  Tercero  Nueva
25        26  Antigua y Barbuda        0        1        2    0.0
26        27           Honduras        0        1        1    0.0
27        28             Panam         0        0        4    0.0
28        29          Nicaragua        0        0        3    0.0
29        30              Aruba        0        0        1    0.0
30        30            Bahamas        0        0        1    0.0
31        32            Surinam        0        0        0    NaN
------------------------------------------
          Posicion    Segundo    Tercero  Nueva
Primero
0        28.857143   0.285714   1.714286    0.0
1        21.375000   1.250000   1.500000    0.0
2        16.500000   8.500000   5.500000    0.0
3        15.000000   0.000000   1.000000    0.0
5        14.000000   5.000000  14.000000    0.0
6        13.000000   6.000000   7.000000    0.0
9        12.000000  15.000000  19.000000    0.0
10       10.500000  10.000000  15.500000    0.0
11        9.000000   7.000000  21.000000    0.0
13        8.000000  19.000000  18.000000    0.0
28        7.000000  23.000000  33.000000    0.0
32        6.000000  35.000000  34.000000    0.0
33        5.000000  27.000000  38.000000    0.0
35        4.000000  64.000000  53.000000    0.0
37        3.000000  36.000000  63.000000    0.0
55        2.000000  45.000000  71.000000    0.0
120       1.000000  88.000000  85.000000    0.0

<ipython-input-70-cbea3c1ed480>:13: FutureWarning: The provided callable <function mean at 0x78f973d05ee0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  print(df.groupby('Primero').agg(np.mean))